### PR TITLE
Add favicon

### PR DESCRIPTION
**Pull request by epwinchell**
Jira: https://issues.redhat.com/browse/RHCLOUD-25990

Screenshot 2023-06-01 at 11 57 13 AM

### CODE REVIEW

**Comment by josejulio** [comment]
I'm confused, this is the favicon I'm seeing at https://developers.redhat.com/ 
Where did this one came from? 

screenshot_2023-06-01T11:25:59

**Comment by epwinchell** [comment]
@josejulio I grabbed it from the QA site... - I'll switch it out

**Comment by josejulio** [comment]
The black one is the new one.

**Review by josejulio — APPROVED** [review]
lgtm

**Pull request merged**
