### PR TITLE
Dynamic paginated content

### PR DESCRIPTION
**Pull request by josejulio**
Adjusts the pagination parameters based on the width of the cards

screenshot_2023-03-21T10:04:02

screenshot_2023-03-21T10:04:15

### CODE REVIEW

**Comment by tahmidefaz** [comment]
@josejulio this one is still waiting for Eric's review, right? Or, is this ready to merge?

**Comment by josejulio** [comment]
> @josejulio this one is still waiting for Eric's review, right? Or, is this ready to merge?

It's waiting some other changes  - i'll turn it into a draft.

**Comment by josejulio** [comment]
@tahmidefaz it's ready for review now

**Review by tahmidefaz — APPROVED** [review]
Looks good!

**Pull request merged**
